/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FindFreelancerRouteImport } from './routes/find-freelancer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminAiConfigRouteImport } from './routes/admin.ai-config'
import { Route as AdminAiCostsRouteImport } from './routes/admin.ai-costs'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BieuMauTokenRouteImport } from './routes/bieu-mau.$token'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as DealsDealIdRouteImport } from './routes/deals.$dealId'
import { Route as FreelancerIdRouteImport } from './routes/freelancer.$id'
import { Route as IntakeTokenRouteImport } from './routes/intake.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FindFreelancerRoute = FindFreelancerRouteImport.update({
  id: '/find-freelancer',
  path: '/find-freelancer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiConfigRoute = AdminAiConfigRouteImport.update({
  id: '/ai-config',
  path: '/ai-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiCostsRoute = AdminAiCostsRouteImport.update({
  id: '/ai-costs',
  path: '/ai-costs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BieuMauTokenRoute = BieuMauTokenRouteImport.update({
  id: '/bieu-mau/$token',
  path: '/bieu-mau/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealIdRoute = DealsDealIdRouteImport.update({
  id: '/deals/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerIdRoute = FreelancerIdRouteImport.update({
  id: '/freelancer/$id',
  path: '/freelancer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeTokenRoute = IntakeTokenRouteImport.update({
  id: '/intake/$token',
  path: '/intake/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/find-freelancer': typeof FindFreelancerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/ai-costs': typeof AdminAiCostsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/bieu-mau/$token': typeof BieuMauTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/freelancer/$id': typeof FreelancerIdRoute
  '/intake/$token': typeof IntakeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/find-freelancer': typeof FindFreelancerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/ai-costs': typeof AdminAiCostsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/bieu-mau/$token': typeof BieuMauTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/freelancer/$id': typeof FreelancerIdRoute
  '/intake/$token': typeof IntakeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/find-freelancer': typeof FindFreelancerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/ai-costs': typeof AdminAiCostsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/bieu-mau/$token': typeof BieuMauTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/freelancer/$id': typeof FreelancerIdRoute
  '/intake/$token': typeof IntakeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/find-freelancer'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/admin/ai-config'
    | '/admin/ai-costs'
    | '/admin/audit'
    | '/admin/plans'
    | '/admin/templates'
    | '/admin/users'
    | '/bieu-mau/$token'
    | '/clients/$clientId'
    | '/deals/$dealId'
    | '/freelancer/$id'
    | '/intake/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/find-freelancer'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/admin/ai-config'
    | '/admin/ai-costs'
    | '/admin/audit'
    | '/admin/plans'
    | '/admin/templates'
    | '/admin/users'
    | '/bieu-mau/$token'
    | '/clients/$clientId'
    | '/deals/$dealId'
    | '/freelancer/$id'
    | '/intake/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/find-freelancer'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/admin/ai-config'
    | '/admin/ai-costs'
    | '/admin/audit'
    | '/admin/plans'
    | '/admin/templates'
    | '/admin/users'
    | '/bieu-mau/$token'
    | '/clients/$clientId'
    | '/deals/$dealId'
    | '/freelancer/$id'
    | '/intake/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FindFreelancerRoute: typeof FindFreelancerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  BieuMauTokenRoute: typeof BieuMauTokenRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  DealsDealIdRoute: typeof DealsDealIdRoute
  FreelancerIdRoute: typeof FreelancerIdRoute
  IntakeTokenRoute: typeof IntakeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-freelancer': {
      id: '/find-freelancer'
      path: '/find-freelancer'
      fullPath: '/find-freelancer'
      preLoaderRoute: typeof FindFreelancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-config': {
      id: '/admin/ai-config'
      path: '/ai-config'
      fullPath: '/admin/ai-config'
      preLoaderRoute: typeof AdminAiConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-costs': {
      id: '/admin/ai-costs'
      path: '/ai-costs'
      fullPath: '/admin/ai-costs'
      preLoaderRoute: typeof AdminAiCostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bieu-mau/$token': {
      id: '/bieu-mau/$token'
      path: '/bieu-mau/$token'
      fullPath: '/bieu-mau/$token'
      preLoaderRoute: typeof BieuMauTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealId': {
      id: '/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof DealsDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/$id': {
      id: '/freelancer/$id'
      path: '/freelancer/$id'
      fullPath: '/freelancer/$id'
      preLoaderRoute: typeof FreelancerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$token': {
      id: '/intake/$token'
      path: '/intake/$token'
      fullPath: '/intake/$token'
      preLoaderRoute: typeof IntakeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiConfigRoute: typeof AdminAiConfigRoute
  AdminAiCostsRoute: typeof AdminAiCostsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiConfigRoute: AdminAiConfigRoute,
  AdminAiCostsRoute: AdminAiCostsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FindFreelancerRoute: FindFreelancerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  BieuMauTokenRoute: BieuMauTokenRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  DealsDealIdRoute: DealsDealIdRoute,
  FreelancerIdRoute: FreelancerIdRoute,
  IntakeTokenRoute: IntakeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
